using Xunit;

namespace vosita_backend_task.EntityFrameworkCore;

[CollectionDefinition(vosita_backend_taskTestConsts.CollectionDefinitionName)]
public class vosita_backend_taskEntityFrameworkCoreCollection : ICollectionFixture<vosita_backend_taskEntityFrameworkCoreFixture>
{

}
