using vosita_backend_task.EntityFrameworkCore;
using Xunit;

namespace vosita_backend_task.EntityFrameworkCore;

public class vosita_backend_taskEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<vosita_backend_taskEntityFrameworkCoreFixture>
{

}
